version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci:"
    target-branch: "main"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build:"
    target-branch: "main"
    groups:
      "minor-and-patch":
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      "major":
        patterns:
          - "*"
