name: 'Setup JDK'
description: 'Set up JDK'

inputs:
  java-version:
    description: 'Java version'
    required: true
    default: '8'

runs:
  using: 'composite'
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
