name: Release

on:
  push:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch:

permissions:
  contents: write
  discussions: write
  pull-requests: write

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      publish_snapshot: false
  release:
    name: Create Release
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs: [tests]
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Setup JDK
      - name: Setup JDK
        uses: ./.github/actions/jdk
        with:
          java-version: ${{ matrix.java }}

      # Setup Gradle & Verify wrapper
      - name: Setup Gradle
        uses: ./.github/actions/gradle

      # Makes the next semantic tag variable available for use in workflow
      - uses: jveldboom/action-conventional-versioning@v1
        id: version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          default-bump: patch
      
      # Build with Gradle & Publish to Maven repository
      - name: Build with Gradle
        run: ./gradlew clean build publishAllPublicationsToReleasesRepository -PcustomVersion=${{ steps.version.outputs.version }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_NAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_SECRET }}

      # Generate changelog
      - name: Changelog
        uses: ardalanamini/auto-changelog@v4
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat: New Features
            fix: Bug Fixes
            build: Build System & Dependencies
            perf: Performance Improvements
            docs: Documentation
            test: Tests
            refactor: Refactors
            chore: Chores
            ci: CI
            style: Code Style
            revert: Reverts
          default-commit-type: Other Changes
          release-name: ${{ steps.version.outputs.version-with-prefix }}
          mention-authors: true
          mention-new-contributors: true
          include-compare-link: true
          include-pr-links: true
          include-commit-links: true
          semver: true
          use-github-autolink: true

      # Create release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/build/libs/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.version.outputs.version-with-prefix }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-RC-') }}
          generate_release_notes: false
          body: ${{ steps.changelog.outputs.changelog }}